### ISSUE TITLE
Unexpected end of json

### ISSUE THREAD

**Issue by GwartneyDev** [benzend/goalboard-collab#17]
Not quite sure what is happening here. But when testing the register user to make sure the cors was working before inserting into database. 

Im seeing this:
 
![image](https://github.com/benzend/goalboard-collab/assets/150888112/71584d69-d886-47f7-85ae-2e00772690ae)

However it does pass the values to the back end just fine when im logging it out. Just there is no redirect, I tried to test it but could not figure it out just yet.

**Comment by benzend** [comment]
I'm pretty sure that this has been resolved! Reopen if not
